### ISSUE TITLE
PaymentDetailsService: Call method on 'null'

### ISSUE THREAD

**Issue by miguelseuster** [Adyen/adyen-shopware6#207]
The PaymentDetailsService throws an error "Call method on null' when calling it.
In the Shopware 6 OrderTransactionEntity the order is null, so no SalesChannelId of the OrderEntity is retrieved.

<img width="856" alt="Bildschirmfoto 2021-09-01 um 14 57 58" src="https://user-images.githubusercontent.com/2871262/131675312-83b532d8-1ecf-4d81-99f5-9d1a8bd44a9a.png">

**Versions**
Shopware version: 6.4.2.1
Plugin version: 3.0.0
PHP version: ^8.0 | ^7.4

**To Reproduce**
1. Initialize PaymentDetailsService in a controller or an EventListener.
2. Pass the OrderTransactionEntity for the order.
3. Complete an order and check the PaymentDetails

**Expected behavior**
Return PaymentDetails from PaymentDetailsService

**Code Example**

`
........
class OrderEventListener implements EventSubscriberInterface
{
    public function __construct(private LoggerInterface $logger, private OrderService $orderService)
    {
    }

    /*
     * @return array<string, mixed>
     */
    public static function getSubscribedEvents()
    {
        return [
            'state_enter.order_transaction.state.paid' => 'onOrderStatePaidEvent',
        ];
    }

    public function onOrderStatePaidEvent(OrderStateMachineStateChangeEvent $event): void
    {
        try {
            $this->logger->info('Paid order....');
            $order = $event->getOrder();
            if ($order instanceof OrderEntity) {
                $this->getPaymentDetails($order);
            }
        } catch (RuntimeException $exception) {
            $this->logger->critical($exception->getTraceAsString())
            );
        }
    }

    private function getPaymentDetails(OrderEntity $order): void {
        $transaction = ($order->getTransactions())->filterByState(OrderTransactionStates::STATE_PAID)->first();
        $paymentDetails = $this->paymentDetails->getPaymentDetails([], $transaction);
    }
.......
}
`

**Comment by miguelseuster** [comment]
Hello Adyen,

do you have any feedback for me? 

Kind regards

**Comment by peterojo** [comment]
Hi @miguelseuster,
Thanks for reporting this, we will investigate this in internal ticket and we hope to work on a fix soon. 
If you already have a working modification, please consider making a PR, then it can be even faster.

**Comment by peterojo** [comment]
HI @miguelseuster, thanks for your feedback!

If you wish to access the order (`->getOrder()`) on an `OrderTransactionEntity` you have to make sure that the `order` [association](https://developer.shopware.com/docs/guides/plugins/plugins/framework/data-handling/add-data-associations#associations) is fetched along with it.
I see that you are first getting the order transactions from the OrderEntity itself (`$order->getTransactions()`), doing it this way the returned `OrderTransactionEntity` objects will NOT contain the `order` association (i.e. `getOrder()` will be `null`), because `$order->getTransactions()->first()->getOrder()` does not really make sense.

I would recommend that you first fetch your order transactions directly from the database with the `order` association. You can see our [OrderRepository](https://github.com/Adyen/adyen-shopware6/blob/develop/src/Service/Repository/OrderRepository.php) implementation for an example of fetching entities with an association. Feel free to add a method to our [`OrderTransactionRepository`](https://github.com/Adyen/adyen-shopware6/blob/develop/src/Service/Repository/OrderTransactionRepository.php) and make a PR

**Comment by peterojo** [comment]
Hi @miguelseuster since there are no more updates on this, I will assume that the comment above has resolved this issue and close this ticket.
Feel free to reopen this issue of the same problem persists or create a new issue for a different problem.
Thanks for contributing to adyen-shopware6
