### ISSUE TITLE
Cannot declare interface Psr\Log\LoggerAwareInterface, because the name is already in use

### ISSUE THREAD

**Issue by alessandroaussems** [Adyen/adyen-shopware6#215]
**Describe the bug**
Cannot install & activate plugin when required with composer

**Versions**
Shopware version: 6.4.5.1
Plugin version: 3.2.0

**To Reproduce**
1. Require plugin with composer: ```composer require store.shopware.com/adyenpaymentshopware6```
2. Install & Activate plugin ```./bin/console plugin:install --activate AdyenPaymentShopware6```
3. Error is thrown: **Cannot declare interface Psr\Log\LoggerAwareInterface, because the name is already in use**

**Expected behavior**
Plugin is installed & activated

**Screenshots**

![](https://shot.alssndro.be/2BbFau/download)

**Comment by alessandroaussems** [comment]
Downgrading the plugin to version 3.1.0 seems to fix the issue. So I assume in release 3.2.0 something broke

**Comment by peterojo** [comment]
Hi @alessandroaussems,

unfortunately this problem persists because shopware requires that we add the core shopware libraries to the `require` block in our plugin's [composer.json](https://github.com/Adyen/adyen-shopware6/blob/develop/composer.json#L13) file.

Please refer to our [docs](https://docs.adyen.com/plugins/shopware-6#install) for the available installation options

**Comment by GshopMaxime** [comment]
Having the same problem in our deploy flow. The vendor folder in the plugin should not contain the same dependencies as the shopware core. You should remove psr and monolog from this vendor folder, remove the php-webhook-module and php-api-library from dependencies in your composer.json and only autoload them from the included vendor folder. This way your plugin will work both via manual install and via composer install. Right now you're loading dependencies twice by having them required in composer.json and having them manually included in the plugin's vendor folder.

**Comment by alessandroaussems** [comment]
@GshopMaxime Since Adyen clearly doesn't care about fixing this issue. You can fix it by requiring the plugin as "adyen/adyen-shopware6" instead of "store.shopware.com/..." in your composer.json file. This way the dependencies don't cause issues.

**Comment by peterojo** [comment]
HI @GshopMaxime and @alessandroaussems as I mention in my earlier comment, our [docs](https://docs.adyen.com/plugins/shopware-6#install) specify the supported way to install the plugin, please follow the docs. Because of Shopware's marketplace requirements, we have to upload a zipped version of this repo with the vendor folder included. You can download the zip from the marketplace and upload it to your store via the admin interface. Alternatively, if you want to use composer, you can install it directly from here via packagist as @alessandroaussems also mentions.

**Comment by leonwetterich** [comment]
Still seems to be an issue on shopware 6.5.3.3

**Comment by roman-1983** [comment]
@peterojo You can solve this easily by adding this to your composer.json. Then the package will not get installed into the vendor folder.
```
    "replace": {
        "psr/log": "*"
    },
```
