### ISSUE TITLE
[PW-7299] Changes to SalesChannelRepository cause issues with headless sales channels

### ISSUE THREAD

**Issue by GshopMaxime** [Adyen/adyen-shopware6#302]
**Describe the bug**
Changes to SalesChannelRepository cause issues with headless sales channels. The changes incorrectly assume that a default href domain is set for a sales channel (which is not possible for headless sales channels) or that the domain id in the sales channel context is not null. Since both can be null, a third fallback should be added to fetch a domain entity according to the sales channel id (like in version 3.6.0 of the plugin). Currently all of our payments via the Shopware PWA return a failed status even though they went through correctly. 

**Versions**
Shopware version: 6.4.15.1
Plugin version: 3.7.0

**To Reproduce**
1. Setup a headless sales channel
2. Setup a Store API route
3. Make a call to this route using the API access key of the headless sales channel
4. Both hreflangDefaultDomainId and domainId in the sales channel context are null

**Comment by peterojo** [comment]
Hi @GshopMaxime, thanks for taking the time to create this issue. We had to change the previous implementation because in v3.6.0 we were simply fetching the first domain attached to a sales channel, since multiple domains are possible this was causing bugs in cases where multiple domains are used in one sales channel (See #267)
We will investigate the case, as you say, where the headless sales channel context does not contain a domain ID and try to find a way to determine the active domain.

**Comment by GshopMaxime** [comment]
Hi @peterojo 
I understand the change to the implementation but since both methods can return null, a third fallback option should be added.
I usually fetch the domains of the current sales channel and sort them by the languageIdChain in the context object. That way I'm sure I'll always get the best matching domain for the current language.
