### ISSUE TITLE
Failed Transaction State overrides Authorized State

### ISSUE THREAD

**Issue by anothaNj** [Adyen/adyen-shopware6#352]
**Describe the bug**
A payment fails, customer chooses to pay with Klarna successfully. The transaction state is authorized but after 30 minutes it shows the transaction as failed and therefore the order does not get processed further.

**Versions**
Shopware version: 6.4.13.0
Plugin version: 3.8.1

**To Reproduce**
1. Fail a payment with credit card
2. Successfully pay with Klarna Pay Later
3. After 30 minutes the transaction state in the admin shows failed

**Expected behavior**
If any transaction is authorized it should be the transaction status for the order

**Screenshots**
![image](https://user-images.githubusercontent.com/26765837/219392021-82001586-7848-4227-b696-2a39f9131324.png)

**Additional context**
The NotificationService calculates the scheduled processing time for not successful 'AUTHORISATION' notifications 30 minutes later, it's not clear why this is necessary

**Comment by candemiralp** [comment]
Hello @anothaNj ,

Thank you for reaching out to us and raising this issue. Failed AUTHORISATION notifications are postponed exactly for this reason. If the order is closed with the notification just after the first failed payment attempt, the second payment will fail also since the order is closed.

In order to solve that issue, notifications that cancels or closes the orders are postponed 30 minutes intentionally. 

The issue you mentioned is a known issue and it was resolved with [this](https://github.com/Adyen/adyen-shopware6/pull/330) pull request. This solution was released on version 3.9.0. If you upgrade your plugin, issue will be resolved.

Since the issue was handled before, I am closing this issue. If you have further questions, please re-open this issue.

Best Regards,
Can
