### ISSUE TITLE
FrontendProxyController.php - change CartOrderRoute to AbstractCartOrderRoute

### ISSUE THREAD

**Issue by sascha-seyfert** [Adyen/adyen-shopware6#492]
Hello dear Adyen team,
 
There is a bug in the Adyen Shopware 6 plugin. 
 
This error occurs in connection with a third-party plugin.
 
Name of the third-party plugin: Conversion Checkout for Shopware 6
Store: https://store.shopware.com/en/loyxx57434896565m/conversion-checkout-for-shopware-6.html
 
Description of the problem / clear instructions for reproduction:
 
[2024-02-09T08:06:36.056488+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Cannot assign LoyxxSW6ConversionCheckout\Core\Checkout\Cart\SalesChannel\CartOrderRoute to property Adyen\Shopware\Storefront\Controller\FrontendProxyController: :$cartOrderRoute of type Shopware\Core\Checkout\Cart\SalesChannel\CartOrderRoute" at FrontendProxyController.php line 71 {"exception":"[object] (TypeError(code: 0): Cannot assign LoyxxSW6ConversionCheckout\\Core\\Checkout\ \Cart\\SalesChannel\\CartOrderRoute to property Adyen\\Shopware\\Storefront\\Controller\\FrontendProxyController::$cartOrderRoute of type Shopware\\Core\\Checkout\\Cart\\SalesChannel\\CartOrderRoute at /var/www /clients/client1/web2/web/production/releases/193/vendor/adyen/adyen-shopware6/src/Storefront/Controller/FrontendProxyController.php:71)"} []
 
PHP class:
Adyen\Shopware\Storefront\Controller\FrontendProxyController
 
Change:
- private CartOrderRoute $cartOrderRoute;
+ private AbstractCartOrderRoute $cartOrderRoute;

https://github.com/Adyen/adyen-shopware6/blob/a8a59eba9d29b6be1677ba9931dfe66b8e0b2cd8/src/Storefront/Controller/FrontendProxyController.php#L54

**Comment by RokPopov** [comment]
Hi @sascha-seyfert,

Thank you for reporting this issue. I have created an internal ticket for handling this. Once the fix is merged with the `develop` branch, this issue will automatically be closed.

Kind regards,
Rok

**Comment by MelvinAchterhuis** [comment]
@RokPopov , same goes for PostNL:

`Cannot assign PostNL\Shopware6\Controller\StoreApi\ContextSwitchRoute to property Adyen\Shopware\Storefront\Controller\FrontendProxyController::$contextSwitchRoute of type Shopware\Core\System\SalesChannel\SalesChannel\ContextSwitchRoute`

**Comment by AndreasA** [comment]
It seems like this was fixed with 4.0.0 
https://github.com/Adyen/adyen-shopware6/blob/4.0.0/src/Storefront/Controller/FrontendProxyController.php 

but not with 3.16.0 https://github.com/Adyen/adyen-shopware6/blob/3.16.0/src/Storefront/Controller/FrontendProxyController.php

which means that for 6.5 which is the LTS version already the fix is not available.

**Comment by rick7240** [comment]
@RokPopov The problem was fixed in the 4.X version, but not in the 3.X version. Due to the Shopware Version not everyone can update to the 4.X version and is dependent on a bugfix in the 3.X version.

We now have to downgrade to a previous 3.X version. Actually we need the 3.16.1 but because of the ECP-9382-v3 Visa Compliance issue.

Can THIS bug also be fixed in the 3.X version in the short term?

**Comment by adyen-integrations-support** [comment]
Hi,

Thank you for bringing this to our attention. 

We’ll work on addressing this problem in the 3.X version and will ensure that a fix is implemented. Once the fix is available, we’ll notify you.

Thank you for your patience, and please feel free to reach out if you have any additional concerns or questions in the meantime.

Best regards
